# Generated by Django 4.1.7 on 2023-03-19 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="タイトル")),
                ("price", models.CharField(max_length=128, verbose_name="値段")),
                ("description", models.TextField(blank=True, verbose_name="説明")),
                ("image", models.ImageField(upload_to="images")),
            ],
        ),
    ]
